---
name: intellij-server
description: Java and Kotlin by IntelliJ IDEA
homepage: https://www.jetbrains.com/help/intellij-vscode/About-instance.html
licenses:
  - MIT
languages:
  - Kotlin
  - Java
categories:
  - LSP

source:
  id: pkg:generic/IntelliJ/intellij-server@263.6379.0
  download:
    - target: darwin_x64
      files:
        intellij-server.zip: https://download-cdn.jetbrains.com/language-server/intellij-server/{{ version }}/intellij-server-{{ version }}.sit
    - target: darwin_arm64
      files:
        intellij-server.zip: https://download-cdn.jetbrains.com/language-server/intellij-server/{{ version }}/intellij-server-{{ version }}-aarch64.sit
    - target: linux_x64
      files:
        intellij-server.tar.gz: https://download-cdn.jetbrains.com/language-server/intellij-server/{{ version }}/intellij-server-{{ version }}.tar.gz
    - target: linux_arm64
      files:
        intellij-server.tar.gz: https://download-cdn.jetbrains.com/language-server/intellij-server/{{ version }}/intellij-server-{{ version }}-aarch64.tar.gz
    - target: win_x64
      files:
        intellij-server.zip: https://download-cdn.jetbrains.com/language-server/intellij-server/{{ version }}/intellij-server-{{ version }}.win.zip
    - target: win_arm64
      files:
        intellij-server.zip: https://download-cdn.jetbrains.com/language-server/intellij-server/{{ version }}/intellij-server-{{ version }}-aarch64.win.zip

