---
name: lua-language-server
description: A language server that offers Lua language support - programmed in Lua.
homepage: https://github.com/LuaLS/lua-language-server
licenses:
  - MIT
languages:
  - Lua
categories:
  - LSP
source:
  id: pkg:github/LuaLS/lua-language-server@3.14.0
  build:
    run: |
      ./make.sh
      cp -r ./bin/lua-language-server ../lua-language-server1
      rm -rf ./* ./.*
      cp -r ../lua-language-server1 ./lua-language-server
      rm -rf ../lua-language-server1
schemas:
  lsp: vscode:https://raw.githubusercontent.com/LuaLS/vscode-lua/master/package.json
bin:
  lua-language-server: "lua-language-server"
