---
name: lua-language-server
description: A language server that offers Lua language support - programmed in Lua.
homepage: https://github.com/LuaLS/lua-language-server
licenses:
  - MIT
languages:
  - Lua
categories:
  - LSP
source:
  id: pkg:github/LuaLS/lua-language-server@3.15.0
  build:
    run: |
      ./make.sh
      rm -rf 3rd build doc Dockerfile LICENSE log make* README.md test* theme-tokens.md tools ./.*
schemas:
  lsp: vscode:https://raw.githubusercontent.com/LuaLS/vscode-lua/master/package.json
bin:
  lua-language-server: ./bin/lua-language-server

