---
name: java-project-manager
description: |
  Manage Java projects in Visual Studio Code
homepage: https://github.com/microsoft/vscode-java-dependency
licenses:
  - EPL-1.0
languages:
  - Java
categories:
  - LSP
source:
  # renovate:datasource=github-tags
  id: pkg:github/microsoft/vscode-java-dependency@0.24.1
  build:
    run: |
      cd jdtls.ext
      mvn clean package -DskipTests
      cd ..
      cp -r jdtls.ext/com.microsoft.jdtls.ext.core/target/com.microsoft.jdtls.ext.core-0.24.1.jar ..
      rm -rf ./* ./.*
      mv ../com.microsoft.jdtls.ext.core-0.24.1.jar .
