---
name: vscode-spring-boot-tools
description: |
  VS Code Language Server for Spring Boot
  VSCode extension and Language Server providing support for working with Spring Boot application.properties, application.yml and .java files.

  Note: this extension has a dependency on VS Code extension of Language Support for Java™ by Red Hat.
homepage: https://github.com/spring-projects/spring-tools
licenses:
  - EPL-1.0
languages:
  - Java
categories:
  - LSP
source:
  # renovate:datasource=github-release
  id: pkg:generic/spring-projects/spring-tools@5.3.0.RELEASE
  download:
    files:
      vscode-spring-boot.vsix: https://open-vsx.org/api/VMware/vscode-spring-boot/2{{version | strip_prefix "5" | strip_suffix ".RELEASE"}}/file/VMware.vscode-spring-boot-2{{version | strip_prefix "5" | strip_suffix ".RELEASE" }}.vsix
schemas:
  lsp: vscode:https://raw.githubusercontent.com/spring-projects/spring-tools/{{version}}/vscode-extensions/vscode-spring-boot/package.json
