---
name: basedpyright
description: Fork of the Pyright static type checker for Python, with extra Pylance features.
homepage: https://detachhead.github.io/basedpyright
licenses:
  - MIT
languages:
  - Python
categories:
  - LSP
source:
  id: pkg:npm/basedpyright@1.34.0
schemas:
  lsp: vscode:https://raw.githubusercontent.com/DetachHead/basedpyright/v{{version}}/packages/vscode-pyright/package.json
bin:
  basedpyright: npm:basedpyright
  basedpyright-langserver: npm:basedpyright-langserver
