name: kulala-ls
description: A minimal language server for HTTP syntax.
homepage: https://github.com/mistweaverco/kulala-ls
licenses:
  - MIT
languages:
  - http
categories:
  - LSP
source:
  id: pkg:npm/@mistweaverco/kulala-fmt@2.10.0
bin:
  kulala-ls: kulala-ls
