name: spring-boot-tools
description: |
  Provides validation and content assist for Spring Boot `application.properties`,
  `application.yml` properties files. As well as Boot-specific support for
  `.java` files.
homepage: https://github.com/spring-projects/spring-tools
licenses:
  - EPL-1.0
languages:
  - Java SpringBoot
categories:
  - LSP
source:
  id: pkg:github/spring-projects/spring-tools@1.62.0-RC1
  download:
    file: vscode-spring-boot-{{version}}.vsix
