---
name: spring-boot-tools
description: |
  Provides validation and content assist for Spring Boot `application.properties`,
  `application.yml` properties files. As well as Boot-specific support for
  `.java` files.
homepage: https://github.com/spring-projects/spring-tools
licenses:
  - EPL-1.0
languages:
  - Java SpringBoot
categories:
  - LSP
# source:
#   # renovate:datasource=github-tags
#   id: pkg:generic/spring-projects/spring-tools@1.64.0-202506120649
#   download:
#     files:
#       spring-boot.vsix: https://cdn.spring.io/spring-tools/snapshot/vscode-extensions/vscode-spring-boot/vscode-spring-boot-{{version}}.vsix
source:
  id: pkg:openvsx/VMware/vscode-spring-boot@1.64.0
  download:
    file: VMware.vscode-spring-boot-{{version}}.vsix
