name: spring-boot-tools
description: |
  Provides validation and content assist for Spring Boot `application.properties`,
  `application.yml` properties files. As well as Boot-specific support for
  `.java` files.
homepage: https://github.com/spring-projects/spring-tools
licenses:
  - EPL-1.0
languages:
  - Java SpringBoot
categories:
  - LSP
source:
  id: pkg:generic/spring-projects/spring-tools@1.63.0-202504231030
  download:
    files:
      spring-boot.vsix: https://cdn.spring.io/spring-tools/snapshot/vscode-extensions/vscode-spring-boot/vscode-spring-boot-{{version}}.vsix
