---
name: java-debug-adapter
description: The debug server implementation for Java. It conforms to the debugger adapter protocol.
homepage: https://github.com/Microsoft/vscode-java-debug
licenses:
  - EPL-1.0
languages:
  - Java
categories:
  - DAP
source:
  # renovate:datasource=github-tags
  id: pkg:generic/Microsoft/vscode-java-debug@0.59.0
  download:
    files:
      vscode-java-debug.vsix: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscjava/vsextensions/vscode-java-debug/{{version}}/vspackage
share:
  java-debug-adapter/: extension/server/
