---
name: lemminx
description: XML Language Server.
homepage: https://github.com/eclipse/lemminx
licenses:
  - EPL-2.0
languages:
  - XML
categories:
  - LSP
source:
  # renovate:datasource=github-tags
  id: pkg:generic/eclipse/lemminx@0.31.0
  download:
    files:
      lemminx.jar: https://download.eclipse.org/lemminx/releases/{{version}}/org.eclipse.lemminx-uber.jar
