---
name: vscode-java-dependency
description: Visual Studio Code extension for managing Java projects, dependencies, and exporting JAR files
homepage: https://github.com/Microsoft/vscode-java-dependency
licenses:
  - MIT
languages:
  - Java
categories:
  - Runtime
source:
  # renovate:datasource=github-tags
  id: pkg:generic/Microsoft/vscode-java-dependency@0.27.6
  download:
    files:
      vscode-java-dependency.vsix: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscjava/vsextensions/vscode-java-dependency/{{version}}/vspackage
share:
  vscode-java-dependency/: extension/server/

